#!/bin/bash

# ale.csv
psql --command="\COPY (SELECT problem.id AS \"ID\", body.name AS \"Kommun\", to_char(confirmed, 'YYYY-MM-DD') || 'T' || to_char(confirmed, 'HH24:MI:SS') || '+0100' AS \"Bekräftat\", problem.category AS \"Kategori\", CASE WHEN state IN ('fixed - council', 'fixed - user', 'closed') THEN 'Stängd, löst' WHEN state IN ('not responsible', 'unable to fix', 'closed', 'duplicate', 'hidden') THEN 'Stängd, ej löst' ELSE 'Öppen' END AS \"Status\", CASE WHEN state IN ('fixed - council', 'fixed - user', 'closed', 'not responsible', 'unable to fix', 'closed', 'duplicate', 'hidden') THEN ((SELECT created FROM comment WHERE problem_id = problem.id AND problem_state IN ('fixed - council', 'fixed - user', 'closed', 'not responsible', 'unable to fix', 'closed', 'duplicate', 'hidden') ORDER BY created ASC LIMIT 1)::date - whensent::date) ELSE (now()::date - whensent::date) END AS \"Dagar till första stängning (stängd) eller nu (öppen)\", ((SELECT created FROM comment WHERE problem_id = problem.id AND user_id IN (SELECT id FROM users WHERE from_body = problem.bodies_str::integer) ORDER BY created ASC LIMIT 1)::date - whensent::date) AS \"Dagar till första förvaltningssvar\", CASE WHEN lastupdate > whensent THEN 'Ja' ELSE 'Nej' END AS \"Uppdaterad sedan utskick\", CASE WHEN service = 'Android' THEN 'Android (Ej PWA)' WHEN service = 'iOS' THEN 'iOS (Ej PWA)' WHEN service = 'mobile' THEN 'Webb/PWA (Smal skärm)' WHEN service = 'desktop' THEN 'Webb/PWA (Bred skärm)' ELSE 'Webb/PWA (Okänd skämbredd)' END AS \"App\" FROM problem, body WHERE confirmed >= '2015-01-01' AND confirmed < '$(date +"%Y-%m-01")' AND problem.bodies_str::integer = body.id AND confirmed IS NOT NULL AND body.id=148 ORDER BY confirmed) TO '/tmp/ale.csv' WITH CSV HEADER ENCODING 'latin1';" fixmystreet
# ale-open.csv
psql --command="\COPY (SELECT id AS \"ID\", category AS \"Kategori\", to_char(whensent, 'YYYY-MM-DD') AS \"Bekräftat\", title AS \"Titel\" FROM problem WHERE whensent IS NOT NULL AND state NOT IN ('fixed - council', 'fixed - user', 'closed', 'hidden') AND bodies_str='148' ORDER BY category, confirmed) TO '/tmp/ale-open.csv' WITH CSV HEADER ENCODING 'utf8';" fixmystreet
# ale-no-body-response.csv
psql --command="\COPY (SELECT id AS \"ID\", category AS \"Kategori\", to_char(whensent, 'YYYY-MM-DD') AS \"Bekräftat\", title AS \"Titel\" FROM problem WHERE whensent IS NOT NULL AND state NOT IN ('fixed - council', 'fixed - user', 'closed', 'hidden') AND (SELECT created FROM comment WHERE problem_id = problem.id AND user_id IN (SELECT id FROM users WHERE from_body = problem.bodies_str::integer) ORDER BY created ASC LIMIT 1) IS NULL AND bodies_str='148' ORDER BY category, confirmed) TO '/tmp/ale-no-body-response.csv' WITH CSV HEADER ENCODING 'latin1';" fixmystreet
# all.csv
psql --command="\COPY (SELECT problem.id AS \"ID\", body.name AS \"Kommun\", to_char(confirmed, 'YYYY-MM-DD') || 'T' || to_char(confirmed, 'HH24:MI:SS') || '+0100' AS \"Bekräftat\", problem.category AS \"Kategori\", CASE WHEN state IN ('fixed - council', 'fixed - user', 'closed') THEN 'Stängd, löst' WHEN state IN ('not responsible', 'unable to fix', 'closed', 'duplicate', 'hidden') THEN 'Stängd, ej löst' ELSE 'Öppen' END AS \"Status\", CASE WHEN state IN ('fixed - council', 'fixed - user', 'closed', 'not responsible', 'unable to fix', 'closed', 'duplicate', 'hidden') THEN ((SELECT created FROM comment WHERE problem_id = problem.id AND problem_state IN ('fixed - council', 'fixed - user', 'closed', 'not responsible', 'unable to fix', 'closed', 'duplicate', 'hidden') ORDER BY created ASC LIMIT 1)::date - whensent::date) ELSE (now()::date - whensent::date) END AS \"Dagar till första stängning (stängd) eller nu (öppen)\", ((SELECT created FROM comment WHERE problem_id = problem.id AND user_id IN (SELECT id FROM users WHERE from_body = problem.bodies_str::integer) ORDER BY created ASC LIMIT 1)::date - whensent::date) AS \"Dagar till första förvaltningssvar\", CASE WHEN lastupdate > whensent THEN 'Ja' ELSE 'Nej' END AS \"Uppdaterad sedan utskick\", CASE WHEN service = 'Android' THEN 'Android (Ej PWA)' WHEN service = 'iOS' THEN 'iOS (Ej PWA)' WHEN service = 'mobile' THEN 'Webb/PWA (Smal skärm)' WHEN service = 'desktop' THEN 'Webb/PWA (Bred skärm)' ELSE 'Webb/PWA (Okänd skämbredd)' END AS \"App\" FROM problem, body WHERE confirmed >= '2015-01-01' AND confirmed < '$(date +"%Y-%m-01")' AND problem.bodies_str::integer = body.id AND confirmed IS NOT NULL ORDER BY confirmed) TO '/tmp/all.csv' WITH CSV HEADER ENCODING 'latin1';" fixmystreet
